module.exports = {
  RECEIVE_SINGLE_RESPONSE: "RECEIVE_SINGLE_RESPONSE",
  RECEIVE_CREATED_RESPONSE: "RECEIVE_CREATED_RESPONSE",
  RECEIVE_ALL_RESPONSES: "RECEIVE_ALL_RESPONSES",
  RECEIVE_SINGLE_QUESTION: "RECEIVE_SINGLE_QUESTION",
  RECEIVE_NEXT_20_QUESTIONS: "RECEIVE_NEXT_20_QUESTIONS"
};
